modLoader = "kotlinforforge"
loaderVersion = "[5.10.0,)"
license = "MIT"

[[mods]]
modId = "tileglobemc"
version = "0.1.0"
displayName = "TileGlobeMC"
authors = "shBLOCK"
description = ''''''

[[mixins]]
config = "tileglobemc.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"