[package]
name = "tileglobe_utils"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { workspace = true }
derive_more = { workspace = true, features = ["debug", "display", "from", "into"] }

[features]
std = []