[package]
name = "tileglobe-runtime-rp2350"
version = "0.1.0"
edition.workspace = true

[dependencies]
tileglobe = { path = "../../tileglobe" }

embassy-rp = { version = "0.8.0", features = ["rp235xb", "critical-section-impl"] }

embedded-alloc = "0.6.0"